import { createPatch } from 'diff';
import type { WordDetail } from '@/types';

/**
 * Compares two objects and generates a unified diff string (git patch format).
 * @param filename The "filename" to display in the patch header (e.g., 'abfahrt.json').
 * @param original The original object.
 * @param modified The modified object.
 * @returns A string in the unified diff format, or null if there are no changes.
 */
export function generateGitDiffString(filename: string, original: WordDetail, modified: WordDetail): string | null {
    const originalString = JSON.stringify(original, null, 2);
    const modifiedString = JSON.stringify(modified, null, 2);

    // If the strings are identical, no need to generate a patch.
    if (originalString === modifiedString) {
        return null;
    }

    const patch = createPatch(filename, originalString, modifiedString, '', '', { context: 3 });
    
    // The createPatch function sometimes includes a "No newline at end of file" line
    // which we can clean up for better readability if desired.
    const lines = patch.split('\n');
    if (lines[lines.length - 1] === '') {
        lines.pop();
    }
    // Remove the header lines generated by the library, as they are not needed for the email format.
    // The header looks like: "Index: filename\n===================================================================\n"
    const cleanedLines = lines.slice(2);

    return cleanedLines.join('\n');
}